// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/cities_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7956764302115727281),
      name: 'City',
      lastPropertyId: const IdUid(5, 6438148968062474679),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6654732761830482985),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4546657810616887297),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4273629231193640390),
            name: 'cityImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2379871393855675577),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6438148968062474679),
            name: 'isRead',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7956764302115727281),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    City: EntityDefinition<City>(
        model: _entities[0],
        toOneRelations: (City object) => [],
        toManyRelations: (City object) => {},
        getId: (City object) => object.id,
        setId: (City object, int id) {
          object.id = id;
        },
        objectToFB: (City object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final cityImageOffset = fbb.writeString(object.cityImage);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, cityImageOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addBool(4, object.isRead);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = City(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              cityImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              isRead: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 12, false));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [City] entity fields to define ObjectBox queries.
class City_ {
  /// see [City.id]
  static final id = QueryIntegerProperty<City>(_entities[0].properties[0]);

  /// see [City.name]
  static final name = QueryStringProperty<City>(_entities[0].properties[1]);

  /// see [City.cityImage]
  static final cityImage =
      QueryStringProperty<City>(_entities[0].properties[2]);

  /// see [City.description]
  static final description =
      QueryStringProperty<City>(_entities[0].properties[3]);

  /// see [City.isRead]
  static final isRead = QueryBooleanProperty<City>(_entities[0].properties[4]);
}
